#!/usr/bin/env bash

c=clang
flags='-g -ferror-limit=1 -gdwarf-4 -ggdb3 -O0 -std=c11 -Wall -Werror -Wextra -Wno-gnu-folding-constant -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-but-set-variable -Wshadow'
libs='-lcrypt -lcs50 -lm'

set -e

# Check if a file name was provided
if [ -z "$1" ]; then
  echo "Usage: $0 file.c"
  exit 1
fi

# Get the base name of the file (without the .c extension)
base="build/$(basename "$1" .c).o"

mkdir -p build

# Check if the .c file exists
if [ ! -f "$1" ]; then
  echo "File $1 does not exist"
  exit 1
fi

# Check if the .o file exists and is older than the .c file
if [ ! -f "$base" ] || [ "$1" -nt "$base" ]; then
  echo -e "Compiling $1..."
  ${c} ${flags} ${1} -o ${base} ${libs}
fi

# Run the compiled binary
gdb "$base" ${@:2}
